#
# Try to find GLEW library and include path.
# Once done this will define
#
# GLM_FOUND
# GLM_INCLUDE_PATH
# 

FIND_PATH( GLM_INCLUDE_PATH glm/glm.hpp
	${DEPENDENCIES_PATH}/glm
	#${PACKAGE_PREFIX_DIR}/include
)


SET(GLM_FOUND "NO")
if (GLM_INCLUDE_PATH)
	SET(ALL_INCLUDE_PATHS ${ALL_INCLUDE_PATHS} ${GLM_INCLUDE_PATH})
	SET(GLM_FOUND "YES")
    message("EXTERNAL LIBRARY 'GLM' FOUND")
else()
    message(SEND_ERROR "ERROR: EXTERNAL LIBRARY 'GLM' NOT FOUND")
endif (GLM_INCLUDE_PATH)
