#organize files
macro(GroupSources curdir)
	file(GLOB children RELATIVE ${PROJECT_SOURCE_DIR}/${curdir} ${PROJECT_SOURCE_DIR}/${curdir}/*)
	foreach(child ${children})
		if(IS_DIRECTORY ${PROJECT_SOURCE_DIR}/${curdir}/${child})
			GroupSources(${curdir}/${child})
		else()
			#string(REPLACE curdir foldername groupname ${groupname})
			string(REPLACE "/" "\\" groupname ${curdir})
			source_group(${groupname} FILES ${PROJECT_SOURCE_DIR}/${curdir}/${child})
		endif()
	endforeach()
endmacro(GroupSources)

#from glfw
macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()


macro(Setup_defaults _installDir)
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
	if (MINGW)
		SET (CMAKE_INSTALL_PREFIX "${DEPENDENCIES_PATH}/${_installDir}/mingw" CACHE PATH "default install path" FORCE )
		#add_definitions(-DMSVC=0)
	elseif (MSVC)
		SET (CMAKE_INSTALL_PREFIX "${DEPENDENCIES_PATH}/${_installDir}/msvc" CACHE PATH "default install path" FORCE )
		#add_definitions(-DMSVC=1)
	elseif (UNIX)
		SET (CMAKE_INSTALL_PREFIX "${DEPENDENCIES_PATH}/${_installDir}/unix" CACHE PATH "default install path" FORCE )
	else()
		SET (CMAKE_INSTALL_PREFIX "${DEPENDENCIES_PATH}/${_installDir}/unknown" CACHE PATH "default install path" FORCE )
		#add_definitions(-DMSVC=0)
	endif()
endif()

if(WIN32)
	add_definitions(-DWIN32)
endif()
endmacro()
